language: python
python:
# - "2.6"    # Some unit tests don't pass, but everything seems to work
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytz tzlocal
  - pip install 'argparse; python_version < "2.7"'
  - pip install 'configparser; python_version < "3.0"'

# command to run tests.  Must give a concrete location for time-related tests to pass
script:
  - TZ=Canada/Mountain python -m pytest -v
