language: python
python:
# - "2.6"    # Some unit tests don't pass, but everything seems to work
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytz tzlocal
  - pip install 'argparse; python_version < "2.7"'
  - pip install 'configparser; python_version < "3.0"'

# command to run tests
script:
  - python -m pytest -v
