language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt

# command to run tests
script:
  - python -m pytest -v
